# Generated by Django 3.2 on 2021-06-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('eemail', models.EmailField(max_length=50)),
                ('econtact', models.CharField(max_length=15)),
                ('epassword', models.CharField(max_length=50)),
            ],
        ),
    ]
